import { MigrationInterface, QueryRunner } from "typeorm";

export class Initial1731088617864 implements MigrationInterface {
  name = 'Initial1731088617864'

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`CREATE TABLE "country" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "last_modified_date" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted" boolean NOT NULL DEFAULT false, "name" text NOT NULL, "code" character(2) NOT NULL, CONSTRAINT "PK_bf6e37c231c4f4ea56dcd887269" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TABLE "artist_category" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "last_modified_date" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted" boolean NOT NULL DEFAULT false, "name" text NOT NULL, CONSTRAINT "PK_1076467352c95d26ca2a0ff9964" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TABLE "gallery" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "last_modified_date" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted" boolean NOT NULL DEFAULT false, "name" text NOT NULL, "label" text NOT NULL, "description" text, "address" text NOT NULL, "country_id" uuid, "gps" text, "public" boolean NOT NULL DEFAULT false, "user_id" uuid, CONSTRAINT "PK_65d7a1ef91ddafb3e7071b188a0" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE INDEX "IDX_4fc548cce57ba41f15ea0b553a" ON "gallery" ("label") `);
    await queryRunner.query(`CREATE UNIQUE INDEX "IDX_ea33c529d13480d86c432ed0fe" ON "gallery" ("label", "user_id") `);
    await queryRunner.query(`CREATE UNIQUE INDEX "IDX_68ff70b90e0aa03535698e6a9b" ON "gallery" ("name", "user_id") `);
    await queryRunner.query(`CREATE TABLE "resource" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "last_modified_date" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted" boolean NOT NULL DEFAULT false, "name" text NOT NULL, "data" bytea NOT NULL, "mime_type" text NOT NULL, "user_id" uuid, "public" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_e2894a5867e06ae2e8889f1173f" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE UNIQUE INDEX "IDX_251569cbfcdec5ae1e5c12e3ea" ON "resource" ("name", "user_id") `);
    await queryRunner.query(`CREATE TABLE "unity_lamp" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "last_modified_date" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted" boolean NOT NULL DEFAULT false, "x" double precision NOT NULL, "y" double precision NOT NULL, "z" double precision NOT NULL, "range" double precision NOT NULL, "shadow" boolean NOT NULL, "room_id" uuid, CONSTRAINT "PK_2d47d5869510770fb608e578060" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TABLE "unity_item_type" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "last_modified_date" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted" boolean NOT NULL DEFAULT false, "name" text NOT NULL, CONSTRAINT "PK_9d191c6ff43418e07479b7c5f81" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TABLE "unity_item" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "last_modified_date" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted" boolean NOT NULL DEFAULT false, "x" double precision NOT NULL, "y" double precision NOT NULL, "z" double precision NOT NULL, "rotation" double precision NOT NULL, "item_type_id" uuid, "room_id" uuid, CONSTRAINT "PK_53bff2985c17a529f1dbb2f02d5" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TABLE "unity_room" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "last_modified_date" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted" boolean NOT NULL DEFAULT false, "name" text NOT NULL, "x" double precision NOT NULL, "y" double precision NOT NULL, "width" double precision NOT NULL, "height" double precision NOT NULL, "length" double precision NOT NULL, "exhibition_id" uuid, "environment_image_id" uuid, "background_music_id" uuid, CONSTRAINT "PK_197439eb14ec8358f373a5dcae4" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TABLE "unity_wall" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "last_modified_date" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted" boolean NOT NULL DEFAULT false, "x" double precision NOT NULL, "y" double precision NOT NULL, "z" double precision NOT NULL, "rotation" double precision NOT NULL, "width" double precision NOT NULL, "height" double precision NOT NULL, "thick" double precision NOT NULL, "color" text NOT NULL, "opacity" double precision NOT NULL DEFAULT '1', "artwork_id" uuid, "room_id" uuid, CONSTRAINT "PK_5486af2f089dfbdddfff51062f3" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TABLE "unity_image" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "last_modified_date" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted" boolean NOT NULL DEFAULT false, "x" double precision NOT NULL, "y" double precision NOT NULL, "scale" double precision NOT NULL, "artwork_id" uuid, "wall_id" uuid, CONSTRAINT "PK_d31d87b24793f0f8785b437529b" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TABLE "exhibition" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "last_modified_date" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted" boolean NOT NULL DEFAULT false, "name" text NOT NULL, "label" text NOT NULL, "from_date" TIMESTAMP WITH TIME ZONE NOT NULL, "to_date" TIMESTAMP WITH TIME ZONE NOT NULL, "curator" text, "gallery_id" uuid, "active_room_id" uuid, "public" boolean NOT NULL DEFAULT false, CONSTRAINT "REL_78b7b3be3b7c05a5fb8f18bcc8" UNIQUE ("active_room_id"), CONSTRAINT "PK_ddc3afc8e0b4daf3b68d51c31f4" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE INDEX "IDX_97e0c1aebf7bb6cadd45bf029d" ON "exhibition" ("label") `);
    await queryRunner.query(`CREATE UNIQUE INDEX "IDX_a1820c4e8d85363a43cec56b9e" ON "exhibition" ("label", "gallery_id") `);
    await queryRunner.query(`CREATE UNIQUE INDEX "IDX_2becf88a4e3f015adfa793b27d" ON "exhibition" ("name", "gallery_id") `);
    await queryRunner.query(`CREATE TABLE "artwork_genre" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "last_modified_date" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted" boolean NOT NULL DEFAULT false, "name" text NOT NULL, CONSTRAINT "PK_f26b24a7d000a1c941641ccf2a3" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TABLE "artwork_material" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "last_modified_date" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted" boolean NOT NULL DEFAULT false, "name" text NOT NULL, CONSTRAINT "PK_7c33d146172563f78d56c327435" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TABLE "artwork_worktype" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "last_modified_date" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted" boolean NOT NULL DEFAULT false, "name" text NOT NULL, CONSTRAINT "PK_d709e57b2f906ea87cb41dc2c9b" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TABLE "artwork_technique" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "last_modified_date" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted" boolean NOT NULL DEFAULT false, "name" text NOT NULL, CONSTRAINT "PK_44d0c8bdd99faf1c039ffc46752" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TYPE "public"."artwork_ai_mode_enum" AS ENUM('automatic', 'manual')`);
    await queryRunner.query(`CREATE TABLE "artwork" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "last_modified_date" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted" boolean NOT NULL DEFAULT false, "name" text NOT NULL, "label" text NOT NULL, "description" text, "artist_id" uuid, "year" text, "ai_mode" "public"."artwork_ai_mode_enum" NOT NULL DEFAULT 'automatic', "tags" text, "artwork_genre_id" uuid, "artwork_material_id" uuid, "artwork_technique_id" uuid, "artwork_worktype_id" uuid, "measurements" text, "width" integer, "height" integer, "public" boolean NOT NULL DEFAULT false, "nft_id" uuid, "import_id" integer, "image_id" uuid, "image_buffer" bytea, "image_mime_type" text, "protected_image_id" uuid, "protected_image_buffer" bytea, "protected_image_mime_type" text, "unity_image_buffer" bytea, "unity_image_mime_type" text, "thumbnail_buffer" bytea, "thumbnail_mime_type" text, CONSTRAINT "REL_7b6300cac5b0a819cb86dac9a1" UNIQUE ("nft_id"), CONSTRAINT "PK_ee2e7c5ad7226179d4113a96fa8" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE INDEX "IDX_33b5ef5e8fe68d3d60d185c222" ON "artwork" ("label") `);
    await queryRunner.query(`CREATE UNIQUE INDEX "IDX_9c280a1bdbebbe9e1775fe4992" ON "artwork" ("label", "artist_id") `);
    await queryRunner.query(`CREATE UNIQUE INDEX "IDX_721387cc14048bb65fbffe3bd0" ON "artwork" ("name", "artist_id") `);
    await queryRunner.query(`CREATE INDEX "IDX_24182742e3fb75d4f511ffd477" ON "artwork" ("image_id") `);
    await queryRunner.query(`CREATE INDEX "IDX_ff00e5a8afde63d3b4245b3ed6" ON "artwork" ("protected_image_id") `);
    await queryRunner.query(`CREATE TABLE "collection" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "last_modified_date" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted" boolean NOT NULL DEFAULT false, "wallet_id" uuid, "col_data" jsonb NOT NULL, CONSTRAINT "UQ_2dac169ab142c552b38dd26a6fc" UNIQUE ("col_data"), CONSTRAINT "PK_ad3f485bbc99d875491f44d7c85" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TABLE "nft" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "last_modified_date" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted" boolean NOT NULL DEFAULT false, "wallet_id" uuid, "nft_data" jsonb NOT NULL, "collection_id" uuid, CONSTRAINT "UQ_598604e11ddf74819339a86b3a7" UNIQUE ("nft_data"), CONSTRAINT "PK_8f46897c58e23b0e7bf6c8e56b0" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TABLE "wallet" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "last_modified_date" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted" boolean NOT NULL DEFAULT false, "user_id" uuid, "wallet_address" text NOT NULL, CONSTRAINT "UQ_476a9a59985bc92d1d91db035d9" UNIQUE ("wallet_address"), CONSTRAINT "PK_bec464dd8d54c39c54fd32e2334" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TABLE "user" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "last_modified_date" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted" boolean NOT NULL DEFAULT false, "name" text, "label" text NOT NULL, "email" text, "password" text, "description" text, "trial_mint_id" uuid, "trial_mint_claimed" boolean NOT NULL DEFAULT false, "trial_mint_paid" boolean NOT NULL DEFAULT false, "avatar_buffer" bytea, "avatar_mime_type" text, CONSTRAINT "UQ_e12875dfb3b1d92d7d7c5377e22" UNIQUE ("email"), CONSTRAINT "REL_1780c2ccb486468f3750a7e0cd" UNIQUE ("trial_mint_id"), CONSTRAINT "PK_cace4a159ff9f2512dd42373760" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE INDEX "IDX_638b948cf586e693a6d983bb70" ON "user" ("label") `);
    await queryRunner.query(`CREATE INDEX "IDX_e12875dfb3b1d92d7d7c5377e2" ON "user" ("email") `);
    await queryRunner.query(`CREATE TABLE "artist" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "last_modified_date" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted" boolean NOT NULL DEFAULT false, "name" text NOT NULL, "label" text NOT NULL, "born" date, "biography" text, "facebook_profile_link" text, "instagram_profile_link" text, "x_profile_link" text, "country_id" uuid, "artist_category_id" uuid, "public" boolean NOT NULL DEFAULT false, "user_id" uuid, "import_id" integer, "avatar_buffer" bytea, "avatar_mime_type" text, CONSTRAINT "PK_55b76e71568b5db4d01d3e394ed" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE INDEX "IDX_89afc81c53e207ae99e05a5668" ON "artist" ("label") `);
    await queryRunner.query(`CREATE UNIQUE INDEX "IDX_d6210fefb473d332b3677bdb00" ON "artist" ("label", "user_id") `);
    await queryRunner.query(`CREATE UNIQUE INDEX "IDX_94abd1fd27bf2890b3dcd1d714" ON "artist" ("name", "user_id") `);
    await queryRunner.query(`CREATE TABLE "exhibition_artworks_artwork" ("exhibition_id" uuid NOT NULL, "artwork_id" uuid NOT NULL, CONSTRAINT "PK_0812a65b352e50af56b77d32820" PRIMARY KEY ("exhibition_id", "artwork_id"))`);
    await queryRunner.query(`CREATE INDEX "IDX_70fbfc35a92b97fef03361a1de" ON "exhibition_artworks_artwork" ("exhibition_id") `);
    await queryRunner.query(`CREATE INDEX "IDX_0cfb7499e87cfb57f41b5ce500" ON "exhibition_artworks_artwork" ("artwork_id") `);
    await queryRunner.query(`ALTER TABLE "gallery" ADD CONSTRAINT "FK_e4e409f9f0d5c60ba5b28a8bac6" FOREIGN KEY ("country_id") REFERENCES "country"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "gallery" ADD CONSTRAINT "FK_7d957482bdc782cacb0635e4551" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "resource" ADD CONSTRAINT "FK_91986a65607b20ec6bf14061694" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "unity_lamp" ADD CONSTRAINT "FK_1c4ce1f4dcde7edd272e8cea33c" FOREIGN KEY ("room_id") REFERENCES "unity_room"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "unity_item" ADD CONSTRAINT "FK_79faeb86735786bd075b8b7c79c" FOREIGN KEY ("item_type_id") REFERENCES "unity_item_type"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "unity_item" ADD CONSTRAINT "FK_b58a2dd81b3b9b117bfe5111322" FOREIGN KEY ("room_id") REFERENCES "unity_room"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "unity_room" ADD CONSTRAINT "FK_0a6450a988aa35048f44ebffc48" FOREIGN KEY ("exhibition_id") REFERENCES "exhibition"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "unity_room" ADD CONSTRAINT "FK_bf07abef0626e635b3899c56704" FOREIGN KEY ("environment_image_id") REFERENCES "resource"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "unity_room" ADD CONSTRAINT "FK_647518754f7a29c55605d141c7c" FOREIGN KEY ("background_music_id") REFERENCES "resource"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "unity_wall" ADD CONSTRAINT "FK_5936f448cbececa1a4afb674521" FOREIGN KEY ("artwork_id") REFERENCES "artwork"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "unity_wall" ADD CONSTRAINT "FK_30f98d45f4a42b926005c491aa5" FOREIGN KEY ("room_id") REFERENCES "unity_room"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "unity_image" ADD CONSTRAINT "FK_b200239796c473fdc65045a055e" FOREIGN KEY ("artwork_id") REFERENCES "artwork"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "unity_image" ADD CONSTRAINT "FK_165f45cc61a6e147c94887e2f58" FOREIGN KEY ("wall_id") REFERENCES "unity_wall"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "exhibition" ADD CONSTRAINT "FK_497f30f928c186da40871eff78b" FOREIGN KEY ("gallery_id") REFERENCES "gallery"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "exhibition" ADD CONSTRAINT "FK_78b7b3be3b7c05a5fb8f18bcc81" FOREIGN KEY ("active_room_id") REFERENCES "unity_room"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "artwork" ADD CONSTRAINT "FK_1335283ab3e8049b7379df23a8d" FOREIGN KEY ("artist_id") REFERENCES "artist"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "artwork" ADD CONSTRAINT "FK_770697562189202289b5f4f3e9a" FOREIGN KEY ("artwork_genre_id") REFERENCES "artwork_genre"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "artwork" ADD CONSTRAINT "FK_20453937a629c67ade0ca30f9e9" FOREIGN KEY ("artwork_material_id") REFERENCES "artwork_material"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "artwork" ADD CONSTRAINT "FK_4223572cabfddeee3e0bc754f2a" FOREIGN KEY ("artwork_technique_id") REFERENCES "artwork_technique"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "artwork" ADD CONSTRAINT "FK_63261a5d59bfee7777f7e214251" FOREIGN KEY ("artwork_worktype_id") REFERENCES "artwork_worktype"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "artwork" ADD CONSTRAINT "FK_7b6300cac5b0a819cb86dac9a14" FOREIGN KEY ("nft_id") REFERENCES "nft"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "collection" ADD CONSTRAINT "FK_3ca3ce510d3279d38168ddca6f9" FOREIGN KEY ("wallet_id") REFERENCES "wallet"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "nft" ADD CONSTRAINT "FK_5ee1c77855cbd6be6f8db2b01fe" FOREIGN KEY ("wallet_id") REFERENCES "wallet"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "nft" ADD CONSTRAINT "FK_ffe58aa05707db77c2f20ecdbc3" FOREIGN KEY ("collection_id") REFERENCES "collection"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "wallet" ADD CONSTRAINT "FK_72548a47ac4a996cd254b082522" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_1780c2ccb486468f3750a7e0cde" FOREIGN KEY ("trial_mint_id") REFERENCES "nft"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "artist" ADD CONSTRAINT "FK_ed3173abd3bf391b4f04c71d4b9" FOREIGN KEY ("country_id") REFERENCES "country"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "artist" ADD CONSTRAINT "FK_07b8110c52bf2de5c53eb9acf9e" FOREIGN KEY ("artist_category_id") REFERENCES "artist_category"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "artist" ADD CONSTRAINT "FK_01528141d43ba0812a1bd51f1bf" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "exhibition_artworks_artwork" ADD CONSTRAINT "FK_70fbfc35a92b97fef03361a1de3" FOREIGN KEY ("exhibition_id") REFERENCES "exhibition"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    await queryRunner.query(`ALTER TABLE "exhibition_artworks_artwork" ADD CONSTRAINT "FK_0cfb7499e87cfb57f41b5ce5004" FOREIGN KEY ("artwork_id") REFERENCES "artwork"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`ALTER TABLE "exhibition_artworks_artwork" DROP CONSTRAINT "FK_0cfb7499e87cfb57f41b5ce5004"`);
    await queryRunner.query(`ALTER TABLE "exhibition_artworks_artwork" DROP CONSTRAINT "FK_70fbfc35a92b97fef03361a1de3"`);
    await queryRunner.query(`ALTER TABLE "artist" DROP CONSTRAINT "FK_01528141d43ba0812a1bd51f1bf"`);
    await queryRunner.query(`ALTER TABLE "artist" DROP CONSTRAINT "FK_07b8110c52bf2de5c53eb9acf9e"`);
    await queryRunner.query(`ALTER TABLE "artist" DROP CONSTRAINT "FK_ed3173abd3bf391b4f04c71d4b9"`);
    await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_1780c2ccb486468f3750a7e0cde"`);
    await queryRunner.query(`ALTER TABLE "wallet" DROP CONSTRAINT "FK_72548a47ac4a996cd254b082522"`);
    await queryRunner.query(`ALTER TABLE "nft" DROP CONSTRAINT "FK_ffe58aa05707db77c2f20ecdbc3"`);
    await queryRunner.query(`ALTER TABLE "nft" DROP CONSTRAINT "FK_5ee1c77855cbd6be6f8db2b01fe"`);
    await queryRunner.query(`ALTER TABLE "collection" DROP CONSTRAINT "FK_3ca3ce510d3279d38168ddca6f9"`);
    await queryRunner.query(`ALTER TABLE "artwork" DROP CONSTRAINT "FK_7b6300cac5b0a819cb86dac9a14"`);
    await queryRunner.query(`ALTER TABLE "artwork" DROP CONSTRAINT "FK_63261a5d59bfee7777f7e214251"`);
    await queryRunner.query(`ALTER TABLE "artwork" DROP CONSTRAINT "FK_4223572cabfddeee3e0bc754f2a"`);
    await queryRunner.query(`ALTER TABLE "artwork" DROP CONSTRAINT "FK_20453937a629c67ade0ca30f9e9"`);
    await queryRunner.query(`ALTER TABLE "artwork" DROP CONSTRAINT "FK_770697562189202289b5f4f3e9a"`);
    await queryRunner.query(`ALTER TABLE "artwork" DROP CONSTRAINT "FK_1335283ab3e8049b7379df23a8d"`);
    await queryRunner.query(`ALTER TABLE "exhibition" DROP CONSTRAINT "FK_78b7b3be3b7c05a5fb8f18bcc81"`);
    await queryRunner.query(`ALTER TABLE "exhibition" DROP CONSTRAINT "FK_497f30f928c186da40871eff78b"`);
    await queryRunner.query(`ALTER TABLE "unity_image" DROP CONSTRAINT "FK_165f45cc61a6e147c94887e2f58"`);
    await queryRunner.query(`ALTER TABLE "unity_image" DROP CONSTRAINT "FK_b200239796c473fdc65045a055e"`);
    await queryRunner.query(`ALTER TABLE "unity_wall" DROP CONSTRAINT "FK_30f98d45f4a42b926005c491aa5"`);
    await queryRunner.query(`ALTER TABLE "unity_wall" DROP CONSTRAINT "FK_5936f448cbececa1a4afb674521"`);
    await queryRunner.query(`ALTER TABLE "unity_room" DROP CONSTRAINT "FK_647518754f7a29c55605d141c7c"`);
    await queryRunner.query(`ALTER TABLE "unity_room" DROP CONSTRAINT "FK_bf07abef0626e635b3899c56704"`);
    await queryRunner.query(`ALTER TABLE "unity_room" DROP CONSTRAINT "FK_0a6450a988aa35048f44ebffc48"`);
    await queryRunner.query(`ALTER TABLE "unity_item" DROP CONSTRAINT "FK_b58a2dd81b3b9b117bfe5111322"`);
    await queryRunner.query(`ALTER TABLE "unity_item" DROP CONSTRAINT "FK_79faeb86735786bd075b8b7c79c"`);
    await queryRunner.query(`ALTER TABLE "unity_lamp" DROP CONSTRAINT "FK_1c4ce1f4dcde7edd272e8cea33c"`);
    await queryRunner.query(`ALTER TABLE "resource" DROP CONSTRAINT "FK_91986a65607b20ec6bf14061694"`);
    await queryRunner.query(`ALTER TABLE "gallery" DROP CONSTRAINT "FK_7d957482bdc782cacb0635e4551"`);
    await queryRunner.query(`ALTER TABLE "gallery" DROP CONSTRAINT "FK_e4e409f9f0d5c60ba5b28a8bac6"`);
    await queryRunner.query(`DROP INDEX "public"."IDX_0cfb7499e87cfb57f41b5ce500"`);
    await queryRunner.query(`DROP INDEX "public"."IDX_70fbfc35a92b97fef03361a1de"`);
    await queryRunner.query(`DROP TABLE "exhibition_artworks_artwork"`);
    await queryRunner.query(`DROP INDEX "public"."IDX_94abd1fd27bf2890b3dcd1d714"`);
    await queryRunner.query(`DROP INDEX "public"."IDX_d6210fefb473d332b3677bdb00"`);
    await queryRunner.query(`DROP INDEX "public"."IDX_89afc81c53e207ae99e05a5668"`);
    await queryRunner.query(`DROP TABLE "artist"`);
    await queryRunner.query(`DROP INDEX "public"."IDX_e12875dfb3b1d92d7d7c5377e2"`);
    await queryRunner.query(`DROP INDEX "public"."IDX_638b948cf586e693a6d983bb70"`);
    await queryRunner.query(`DROP TABLE "user"`);
    await queryRunner.query(`DROP TABLE "wallet"`);
    await queryRunner.query(`DROP TABLE "nft"`);
    await queryRunner.query(`DROP TABLE "collection"`);
    await queryRunner.query(`DROP INDEX "public"."IDX_ff00e5a8afde63d3b4245b3ed6"`);
    await queryRunner.query(`DROP INDEX "public"."IDX_24182742e3fb75d4f511ffd477"`);
    await queryRunner.query(`DROP INDEX "public"."IDX_721387cc14048bb65fbffe3bd0"`);
    await queryRunner.query(`DROP INDEX "public"."IDX_9c280a1bdbebbe9e1775fe4992"`);
    await queryRunner.query(`DROP INDEX "public"."IDX_33b5ef5e8fe68d3d60d185c222"`);
    await queryRunner.query(`DROP TABLE "artwork"`);
    await queryRunner.query(`DROP TYPE "public"."artwork_ai_mode_enum"`);
    await queryRunner.query(`DROP TABLE "artwork_technique"`);
    await queryRunner.query(`DROP TABLE "artwork_worktype"`);
    await queryRunner.query(`DROP TABLE "artwork_material"`);
    await queryRunner.query(`DROP TABLE "artwork_genre"`);
    await queryRunner.query(`DROP INDEX "public"."IDX_2becf88a4e3f015adfa793b27d"`);
    await queryRunner.query(`DROP INDEX "public"."IDX_a1820c4e8d85363a43cec56b9e"`);
    await queryRunner.query(`DROP INDEX "public"."IDX_97e0c1aebf7bb6cadd45bf029d"`);
    await queryRunner.query(`DROP TABLE "exhibition"`);
    await queryRunner.query(`DROP TABLE "unity_image"`);
    await queryRunner.query(`DROP TABLE "unity_wall"`);
    await queryRunner.query(`DROP TABLE "unity_room"`);
    await queryRunner.query(`DROP TABLE "unity_item"`);
    await queryRunner.query(`DROP TABLE "unity_item_type"`);
    await queryRunner.query(`DROP TABLE "unity_lamp"`);
    await queryRunner.query(`DROP INDEX "public"."IDX_251569cbfcdec5ae1e5c12e3ea"`);
    await queryRunner.query(`DROP TABLE "resource"`);
    await queryRunner.query(`DROP INDEX "public"."IDX_68ff70b90e0aa03535698e6a9b"`);
    await queryRunner.query(`DROP INDEX "public"."IDX_ea33c529d13480d86c432ed0fe"`);
    await queryRunner.query(`DROP INDEX "public"."IDX_4fc548cce57ba41f15ea0b553a"`);
    await queryRunner.query(`DROP TABLE "gallery"`);
    await queryRunner.query(`DROP TABLE "artist_category"`);
    await queryRunner.query(`DROP TABLE "country"`);
  }

}
